// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://maourawciifennrsivps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hb3VyYXdjaWlmZW5ucnNpdnBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NDkyMzEsImV4cCI6MjA3NDAyNTIzMX0.vyHiZUKXPO7y3D9GHRU0HKiZQruJ5tsBEk4LCGmolgM";

// Safe localStorage access to prevent errors in environments where localStorage is not available
const getSafeLocalStorage = () => {
  try {
    // Check if we're in a browser environment
    if (typeof window !== 'undefined' && typeof window.localStorage !== 'undefined') {
      return localStorage;
    }
    return null;
  } catch (error) {
    console.warn('localStorage is not available:', error);
    return null;
  }
};

// Import the supabase client like this:
// import { supabase } from "@core/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: getSafeLocalStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});
