[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (if needed)
# [build.environment]
#   VITE_SUPABASE_URL = "your-supabase-url"
#   VITE_SUPABASE_ANON_KEY = "your-supabase-anon-key"
