// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://maourawciifennrsivps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hb3VyYXdjaWlmZW5ucnNpdnBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NDkyMzEsImV4cCI6MjA3NDAyNTIzMX0.vyHiZUKXPO7y3D9GHRU0HKiZQruJ5tsBEk4LCGmolgM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});